id: http://which-cmd.dev
description: Schema for which-cmd configuration files
type: object
properties:
  keys:
    type: array
    items:
      $ref: "#/definitions/Node"
definitions:
  Node:
    type: object
    properties:
      key:
        type: string
        pattern: ^.$
      keys:
        type: array
        items:
          $ref: "#/definitions/Node"
